/* Game.vapi generated by valac 0.56.3, do not modify. */

namespace Sandbox {
	[CCode (cheader_filename = "sandbox/Game.h")]
	public class TestGame : Virgil.Game {
		public TestGame ();
		public override void draw ();
		public override void init ();
		public override void update (float delta_time);
	}
}
[CCode (cheader_filename = "sandbox/Game.h")]
[ModuleInit]
public static GLib.Type register_game (GLib.Module module);
